CREATE ROLE booking_runtime NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS CONNECTION LIMIT 5;
GRANT CONNECT ON DATABASE postgres TO booking_runtime;
GRANT USAGE ON SCHEMA booking TO booking_runtime;
GRANT SELECT ON booking.doctor TO booking_runtime;
CREATE POLICY runtime_read ON booking.doctor FOR SELECT TO booking_runtime USING (true);
GRANT SELECT ON booking.slot TO booking_runtime;
CREATE POLICY runtime_read ON booking.slot FOR SELECT TO booking_runtime USING (true);
GRANT SELECT ON booking.doctor_leave TO booking_runtime;
CREATE POLICY runtime_read ON booking.doctor_leave FOR SELECT TO booking_runtime USING (true);
GRANT SELECT ON booking.patient TO booking_runtime;
CREATE POLICY runtime_read ON booking.patient FOR SELECT TO booking_runtime USING (true);
GRANT SELECT, INSERT, UPDATE ON booking.bookings TO booking_runtime;
CREATE POLICY runtime_read ON booking.bookings FOR SELECT TO booking_runtime USING (true);
CREATE POLICY runtime_insert ON booking.bookings FOR INSERT TO booking_runtime WITH CHECK (true);
CREATE POLICY runtime_update ON booking.bookings FOR UPDATE TO booking_runtime USING (true) WITH CHECK (true);
GRANT SELECT, INSERT, UPDATE ON booking.patient_session TO booking_runtime;
CREATE POLICY runtime_read ON booking.patient_session FOR SELECT TO booking_runtime USING (true);
CREATE POLICY runtime_insert ON booking.patient_session FOR INSERT TO booking_runtime WITH CHECK (true);
CREATE POLICY runtime_update ON booking.patient_session FOR UPDATE TO booking_runtime USING (true) WITH CHECK (true);
GRANT SELECT, INSERT ON booking.operation TO booking_runtime;
CREATE POLICY runtime_read ON booking.operation FOR SELECT TO booking_runtime USING (true);
CREATE POLICY runtime_insert ON booking.operation FOR INSERT TO booking_runtime WITH CHECK (true);
GRANT SELECT ON public.alembic_version TO booking_runtime;
CREATE POLICY runtime_read ON public.alembic_version FOR SELECT TO booking_runtime USING (true);
